### PR TITLE
added script file

### PR DESCRIPTION
**Pull request by sck916**
added script file

### CODE REVIEW

**Review by zsmeltz — APPROVED** [review]
Hell yeah, man!

**Review by zsmeltz — APPROVED** [review]
Sweet

**Review by zsmeltz — APPROVED** [review]
Yeah

**Review by zsmeltz — APPROVED** [review]
Awesome!

**Review by zsmeltz — APPROVED** [review]
awesome!

**Review by PCeeeZy — APPROVED** [review]
get wrecked

**Pull request merged**
